import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#9df3dc',
        'secondary-container': '#41fda8',
        'tertiary': '#41485e',
        'on-primary-fixed-variant': '#005143',
        'inverse-surface': '#2d3133',
        'surface-container-low': '#f2f4f1',
        'on-primary-container': '#96ebd5',
        'on-tertiary-container': '#d4dbf5',
        'primary-container': '#005344',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'background': '#f8faf7',
        'inverse-primary': '#81d6c0',
        'surface-container-high': '#e6e9e6',
        'primary': '#005344',
        'outline-variant': '#bec9c4',
        'on-primary-fixed': '#00201a',
        'surface-bright': '#f8faf7',
        'on-secondary-container': '#007146',
        'on-primary': '#ffffff',
        'on-background': '#191c1e',
        'on-error-container': '#93000a',
        'on-tertiary': '#ffffff',
        'surface-container-highest': '#e1e3e0',
        'surface-dim': '#d8dbd8',
        'surface': '#f8faf7',
        'secondary-fixed': '#52ffac',
        'tertiary-container': '#586076',
        'on-tertiary-fixed-variant': '#3f465c',
        'secondary-fixed-dim': '#00e290',
        'on-secondary-fixed-variant': '#005231',
        'surface-variant': '#e0e3e5',
        'on-secondary-fixed': '#002111',
        'outline': '#6e7975',
        'on-surface-variant': '#3f4945',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#dae2fd',
        'secondary': '#006d43',
        'surface-tint': '#006b59',
        'inverse-on-surface': '#eff1f3',
        'tertiary-fixed-dim': '#bec6e0',
        'on-surface': '#191c1b',
        'error-container': '#ffdad6',
        'surface-container': '#eceeec',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#131b2e',
        'primary-fixed-dim': '#81d6c0',
        'amber': '#a35d00',
        'amber-bg': '#fdecd1',
        'red-text': '#93000a',
        'red-bg': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        display: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
};

export default config;
