export const SUBJECTS_BY_YEAR: Record<number, string[]> = {
  1: [
    'basic_electrical_engineering',
    'basic_electronics_engineering',
    'engineering_mathematics_1',
    'engineering_mathematics_2',
    'engineering_physics',
    'programming_in_c',
    'workshop_practice',
  ],
  2: [
    'electronic_devices_and_circuits',
    'digital_electronics_and_logic_design',
    'network_theory',
    'signals_and_systems',
    'analog_electronics',
    'electromagnetic_field_theory',
    'data_structures',
    'microcontrollers_and_embedded_systems',
  ],
  3: [
    'microprocessors_and_microcontrollers',
    'communication_systems',
    'digital_signal_processing',
    'vlsi_design',
    'embedded_systems',
    'control_systems',
    'linear_integrated_circuits',
    'analog_and_digital_communication',
  ],
  4: [
    'wireless_and_mobile_communication',
    'microwave_engineering_and_antennas',
    'optical_fiber_communication',
    'iot_and_industry_4',
    'advanced_communication_systems',
    'final_year_project',
    'technical_seminar',
    'vlsi_design_lab_advanced',
  ],
};

export const SUBJECT_LABELS: Record<string, string> = {
  basic_electrical_engineering:         'Basic Electrical Engineering',
  basic_electronics_engineering:        'Basic Electronics Engineering',
  engineering_mathematics_1:            'Engineering Mathematics I',
  engineering_mathematics_2:            'Engineering Mathematics II',
  engineering_physics:                  'Engineering Physics',
  programming_in_c:                     'Programming in C',
  workshop_practice:                    'Workshop Practice',
  electronic_devices_and_circuits:      'Electronic Devices & Circuits',
  digital_electronics_and_logic_design: 'Digital Electronics & Logic Design',
  network_theory:                       'Network Theory',
  signals_and_systems:                  'Signals & Systems',
  analog_electronics:                   'Analog Electronics',
  electromagnetic_field_theory:         'Electromagnetic Field Theory',
  data_structures:                      'Data Structures',
  microcontrollers_and_embedded_systems:'Microcontrollers & Embedded Systems',
  microprocessors_and_microcontrollers: 'Microprocessors & Microcontrollers',
  communication_systems:                'Communication Systems',
  digital_signal_processing:            'Digital Signal Processing',
  vlsi_design:                          'VLSI Design',
  embedded_systems:                     'Embedded Systems',
  control_systems:                      'Control Systems',
  linear_integrated_circuits:           'Linear Integrated Circuits',
  analog_and_digital_communication:     'Analog & Digital Communication',
  wireless_and_mobile_communication:    'Wireless & Mobile Communication',
  microwave_engineering_and_antennas:   'Microwave Engineering & Antennas',
  optical_fiber_communication:          'Optical Fiber Communication',
  iot_and_industry_4:                   'IoT & Industry 4.0',
  advanced_communication_systems:       'Advanced Communication Systems',
  final_year_project:                   'Final Year Project',
  technical_seminar:                    'Technical Seminar',
  vlsi_design_lab_advanced:             'VLSI Design Lab (Advanced)',
};
